<?php

// Gestion order (sql)
class ORDER_ENUM{
	const ORDER_GET = "order";
	const ORDER_DIRECTION = "order_direction";
	const ORDER_DIRECTION_ASC = "asc";
	const ORDER_DIRECTION_DESC = "desc";
	const ORDER_DIRECTION_NO = "no";
}

// param table
$TABLE_SIZE = "table_size";
$TABLE_ID = "table_id";
$TABLE_OTHER = "table_other";
$TABLE_FORM_INFO = "TABLE_FORM_INFO";

// gestion table pour sql
$CONDITION_GET = "condition";
$SHOW_COL_COUNT = "show_col_count";
$COLUMNS_SUMMARY = "columns_summary";
$COLUMNS_FILTER = "columns_filtered";
$TABLE_NAME = "TABLE_NAME";
$TABLE_ROW_FIRST = "TABLE_ROW_FIRST";
$TABLE_ROW_LIMIT = "TABLE_ROW_LIMIT";
$TABLE_WHERE_ID_KEY = "TABLE_WHERE_KEY";
$TABLE_WHERE_ID_VALUE = "TABLE_WHERE_VALUE";
$TABLE_WHERE_CONDITION = "TABLE_WHERE_CONDITION";
$TABLE_WHERE_CONDITION_FOR_UPDATE = "TABLE_WHERE_CONDITION_FOR_UPDATE";
$TABLE_DISTINCT = "USE_SELECT_DISTINCT";

// gestion table insert,update,delete
$TABLE_FORM_NAME_INSERT = "TABLE_FORM_NAME";
$TABLE_INSERT = "TABLE_INSERT";
$TABLE_UPDATE = "TABLE_UPDATE";
$TABLE_DELETE = "TABLE_DELETE";
$TABLE_EDIT = "TABLE_EDIT";
$TABLE_DELETE_BY_ROW = "TABLE_DELETE_BY_ROW";
$TABLE_EDIT_BY_ROW = "TABLE_EDIT_BY_ROW";
$TABLE_EXPORT_CSV = "TABLE_EXPORT_CSV";



?>